# SASS-Linter Options
options:

  # don't merge default rules
  merge-default-rules: false

# File Options
max-warnings: 2
files:
  include: '**/*.s+(a|c)ss'

# Rule Configuration https://github.com/sasstools/sass-lint/tree/master/docs/rules
## 0 = ignore
## 1 = warnings
## 2 = error
rules:

  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
      - mq

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 0
  no-debug: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-zero: 2
  no-trailing-whitespace: 2
  no-transition-all: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 0
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 1
    - max-depth: 10

  # Name Formats
  class-name-format:
    - 2
    - convention: 'hyphenatedlowercase'
  function-name-format: 2
  id-name-format: 0
  mixin-name-format:
    - 2
    - convention: 'camelcase'
  placeholder-name-format:
    - 2
    - convention: 'hyphenatedlowercase'
  variable-name-format:
    - 2
    - convention: 'camelcase'

  # Style Guide
  bem-depth: 2
  border-zero: 0
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length: 2
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 4
  leading-zero: 2
  property-sort-order:
    - 2
    - order: 'alphabetical'
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property:
    - 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens:
    - 2
    - include: false
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2