version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3360:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - gulpwordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8002:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - gulpwordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8080:80'
    volumes:
      - ./wwwroot:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - gulpwordpress

  wpcli:
    image: tatemz/wp-cli
    volumes:
      - ./wwwroot:/var/www/html
    restart: always
    ports:
      - '8001:80'
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

networks:
  gulpwordpress:
volumes:
  db_data:
